### PR TITLE
Dockerizing nkd.su

### PR DESCRIPTION
**Pull request by tomouchuu**
These commits are what I have done to successfully get nkd.su running locally on my mac.

I'm hoping [docker.md](https://github.com/colons/nkd.su/blob/47a4ba8b0e858ec88d6e7a1feee6666a46040b9c/docker.md) is easy enough to follow and it's the first time I'm using Docker/Docker-Compose myself.

At the moment it's pretty barebones and I would like to automate it more.

Also sorry for the horrendous commit messages again.

### CODE REVIEW

**Comment by Tomo-san** [comment]
TODO:
- [ ] We should run nkdsu's tests at some point during the build to make sure it all went correctly, rather than expecting it to just work.
- [ ] Fix spelling errors, namely 'postgres' which I keep spelling as 'postgress'

**Comment by Tomo-san** [comment]
Note: Run the test command once and after you have upped the containers from a complete wipe and clean build. Then see what the errors (if any) are

**Comment by Tomo-san** [comment]
Dumping things from IRC

Right, https://gist.github.com/Tomo-san/22959e73fbb96c67694b is now definitely the first run. So first file is what happens in the containers and second file is when running the test on the web container.

I wonder if it has anything due to different database configs between our containers and travis. Since travis has no password and we have one. Then again, it shouldn't have been able to create the test database at all surely.

My thinking was wrong, no password on the postgres user still wrong.

Reading into the error points towards the issue being that the show_id key 7 isn't in vote_show when it's trying to add a row to vote_vote with the show_id of 7. Probably blind but don't see the show id being set in the fixtures for vote_show. I did try modify the vote.json fixture and add the field show with 7 as it's value but that supressed the db container telling me about the errors but all tests failed. Same thing happened using "show_id" too in the vote.json for vote.shows

**Comment by Tomo-san** [comment]
I've been updating the fixtures to include the data that the initial tests were complaining about and so it now passes.

Not sure updating the fixtures was the right way to fix it but anyhow. I'll push these commits now but I want to find a better way to build the containers since they're pretty big/long to build.

Might be worth adopting the same sort of system we're doing at my workplace which removes all of the code from the build step and instead mounts it as a volume. Dramatically changes the file structure though.

**Comment by tomopagu** [comment]
Since it's been a few months of my company using Docker I think we've reached a standard where we keep the code within code. Will confirm why but I think it's because it allows us to reproduce the container on any host whereas before you could get inconsistencies so it's worth waiting longer for it to build.

I'll get back to working on this sometime soon

**Comment by colons** [comment]
d(\*⌒▽⌒\*)b

**Pull request closed without merging**
